services:
  - type: web
    plan: free
    name: LLW-MD-V1
    runtime: docker
    region: Frankfurt
    branch: V-3.00
    repo: https://github.com/LLWEDITZ/LLW-MD
    #buildCommand: |
    #  apt-get update && \
    #  apt-get install -y ffmpeg && \
    #  npm install
    autoDeploy: true
    healthCheckPath: /
    #startCommand: npm start
    envVars:
      - key: SESSION_ID
        value: "YOUR_SESSION_ID"
